### PR TITLE
send_message plugin

### PR DESCRIPTION
**Pull request by ashishmore**
The send message plugin can be used to send TCPIP messages to other programs, such as LabScribe Data Acquisition  software, by iWorx Systems Inc.

### CODE REVIEW

**Comment by whiteTyger** [comment]
Hi Ashish,

I have some questions about how to use your plugin. It's not working quite the way I thought it would, so I'm thinking I may be using it incorrectly. I'm trying to use the send_message to place marks into LabScribe 3 while it's recording. The messages I'm sending should have different text for each mark, but all my marks in LabScribe show up as "Experiment Started", rather than the text I specified in the "Enter Message" textbox

**Comment by ashishmore** [comment]
Hi,
  here is an example of using the plugin to send messages to LabScribe3.
This is part of the StroopEffect-OpenSesame experiment included with the
LabScribe complete installer.

please let me know if you have any questions.

-ashish

Ashish More
iWorx Systems Inc.
Dover, NH 03820
603-742 2492 x12

**Comment by whiteTyger** [comment]
Hi Ashish,
I've used the plugin based on what I saw in the StroopEffect-OpenSesame experiment, but all the marks that I see being made in LabScribe still say "Experiment Started" instead of the message specified in the plugin. Is that the expected behavior?

**Comment by ashishmore** [comment]
Hi,
  No, the Experiment Started is the first mark that should be sent by the
plugin.
have you tried running the Stroop effect lab?.

-ashish

Ashish More
iWorx Systems Inc.
Dover, NH 03820
603-742 2492 x12

**Comment by whiteTyger** [comment]
Hi,
I tried running the Stroop effect lab, it does the same thing. Every new mark is labeled as "Experiment Started" instead of the proper message it's supposed to send. I'm using Labscribe 3 and OpenSesame 3.07, not sure if that causes problems.
image

**Comment by ashishmore** [comment]
Hi,
   For some reason, with Opensesame v3 the options are not being set
properly.
I have modified the script to default to send message each time.
The Start experiment and end experiment will not work please replace them
with send message.

Thanks

-ashish

Ashish More
iWorx Systems Inc.
Dover, NH 03820
603-742 2492 x12

On Mon, Mar 28, 2016 at 10:19 PM, whiteTyger <notifications@github.com>
wrote:

> Hi,
> I tried running the Stroop effect lab, it does the same thing. Every new
> mark is labeled as "Experiment Started" instead of the proper message it's
> supposed to send. I'm using Labscribe 3 and OpenSesame 3.07, not sure if
> that causes problems.
> [image: image]
> <https://cloud.githubusercontent.com/assets/11383456/14095963/119e7eda-f533-11e5-9d86-082120db0b14.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/smathot/OpenSesame/pull/246#issuecomment-202669684>
>

from libopensesame import debug
from libopensesame.item import item
from libqtopensesame.items.qtautoplugin import qtautoplugin
from openexp.canvas import canvas
from libopensesame.item import item
from time import gmtime, strftime
from datetime import datetime
from datetime import timedelta


import time
import socket
import sys



class send_message(item):
	description = u'Plugin to send messages to Labscribe.'
				
	def reset(self):
		self._checkbox = u'no' # yes = checked, no = unchecked
		self._color = u'blue'
		self._script = u'print 10'	
		debug.msg(u'send_message plug-in has been initialized!')
		self.host = '127.0.0.1'
		self.port = 3000
		self.startTime = datetime.now()
		self.timeDiff = 0;
	

	def prepare(self):
		item.prepare(self)

	def run(self):
		self.set_item_onset() # Record the timestamp of the plug-in execution.
		try:
			sendmsg_socket = socket.create_connection((self.host, self.port))
			sendmsg_socketCreated = 1
		except socket.error, msg:
			print 'Error Code : ' + str(msg[0]) + ' Message ' + msg[1]

		if sendmsg_socketCreated == 1:
			msg = "markonly^"  + self._text + "^"
			try :
				sendmsg_socket.sendall(msg.encode('utf8'))

			except socket.error, msg:
				print 'Error Code : ' + str(msg[0]) + ' Message ' + msg[1]
		else:
			print 'error'
				
		
		self.set_item_onset() # Record the timestamp of the plug-in execution.

class qtsend_message(send_message, qtautoplugin):

	def __init__(self, name, experiment, script=None):
		send_message.__init__(self, name, experiment, script)
		qtautoplugin.__init__(self, __file__)

	def init_edit_widget(self):
		qtautoplugin.init_edit_widget(self)
	
	def IndexChanged(index):
		if index == 0:
			self.line_edit_widget.setEnabled(true)
		else:
			self.line_edit_widget.setEnabled(false)

	def edit_widget(self):
		qtautoplugin.edit_widget(self)      
		if self.combobox_widget.currentText() == u'Send Message':
			self.line_edit_widget.show()
		else:
			self.line_edit_widget.hide()
		return self._edit_widget

**Comment by smathot** [comment]
Hi guys.

I think it's best to close this pull request and move this plug-in to a separate repository, so the discussion can continue there. @ashishmore is that ok? A small repository with just this plug-in plus some information about how to install it.

Regarding the problem. I'm not sure whether the problem is due to this, but there have been some changes to the plug-in API in OpenSesame 3, as described here:

- http://osdoc.cogsci.nl/plug-ins/create-plug-in/

The main difference is that experimental variables (i.e. the things that you would set using the plug-in controls) are now set as properties of the `var` object. All changes should be backwards compatible, except in some edge cases.

Cheers,
Sebastiaan

**Comment by ashishmore** [comment]
Hi Sebastiaan,
   That is fine with me.  Do I use self.var._option instead of self._option
?


-ashish

Ashish More
iWorx Systems Inc.
Dover, NH 03820
603-742 2492 x12

**Comment by smathot** [comment]
> Do I use self.var._option instead of self._option

Yes, exactly. All the variables that the user changes are set like this, as properties of `self.var`. Variables that are only used internally by the plug-in don't need to be set like this.

**Pull request closed without merging**
