### PR TITLE
Updated Debian packaging (in debian branch) for the latest release

### PR DESCRIPTION
**Pull request by yarikoptic**
so interesting changes are from the merge point

### CODE REVIEW

**Comment by smathot** [comment]
Thank's a lot! I suggest we do this for 2.9.7, which is the next maintenance release which I will tag shortly (say within a month). As you said in your mail, I also have to package [python-qprogedit](https://github.com/smathot/QProgEdit), which is the editor component that I split off to keep things modular and manageable. But since the structure is quite similar, I should be able to adapt the OpenSesame packaging.

Regarding unit testing. The 3.0 series, which lives in the `ising` branch, will have unit testing, and will also be Python 3 compatible. But that branch won't be stable before a while, so I suggest we deal with that when the time comes.

Thanks again!

**Comment by smathot** [comment]
A small question/ comment. When I use these new build scripts, the source archive contains the entire source folder, including the `.git` subfolder and other (for this purpose) irrelevant stuff. This leads to a source archive of almost 1 Gb. I imagine that this is not supposed to happen, right?

**Comment by yarikoptic** [comment]
On Sat, 13 Jun 2015, Sebastiaan Mathot wrote:

>    A small question/ comment. When I use these new build scripts, the source
>    archive contains the entire source folder, including the .git subfolder
>    and other (for this purpose) irrelevant stuff. This leads to a source
>    archive of almost 1 Gb. I imagine that this is not supposed to happen,
>    right?

rright... how do you generate source archive?  git-buildpackage?

**Comment by smathot** [comment]
If you call `python setup.py sdist`, it will create a source archive in the `dist` subfolder (which will be created if it doesn't exist). The structure of the filename is `opensesame-[version].tar.gz`. So for 2.9.6 the source archive would be `dist/opensesame-2.9.6.tar.gz`. This is all handled by `distutils`:

- https://docs.python.org/2/distutils/sourcedist.html

**Comment by yarikoptic** [comment]
sorry -- I have missed the question I guess.  Usually debian packages (maintained in debian, not in upstream repo) indeed just use the source distribution tarballs (like the one generated by setup.py sdist) as their base.  But then the problem comes that source distribution tarballs do not provide "full source":
```
(git)hopa:~exppsy/opensesame[debian]git
$> diff -Naur --exclude=.git --exclude=debian /tmp/opensesame-2.9.6 . | lsdiff 
./dev-scripts/architecture.py
./dev-scripts/check_ts.py
./dev-scripts/compile_qm.sh
./dev-scripts/compile_ui.sh
./dev-scripts/compile_ui-win32.sh
./dev-scripts/docstruct.py
./dev-scripts/extract_translatables.py
./dev-scripts/item-help.py
./dev-scripts/update-hidden.py
./dev-scripts/update_ts.sh
./extensions/example/example.py
./extensions/example/info.yaml
./.gitattributes
./MANIFEST.in
./opensesameandroid.py
./opensesame.nsi
./opensesame_unittest/backends.py
./opensesame_unittest/__init__.py
./opensesame_unittest/parsing.py
./opensesame_unittest/syntax.py
./PKG-INFO
./plugins/auto_example/auto_example_large.png
./plugins/auto_example/auto_example.md
./plugins/auto_example/auto_example.png
./plugins/auto_example/auto_example.py
./plugins/auto_example/info.yaml
./plugins/form_text_render/form_text_render.html
./plugins/form_text_render/form_text_render_large.png
./plugins/form_text_render/form_text_render.png
./plugins/form_text_render/form_text_render.py
./plugins/form_text_render/form_text_render.pyo
./plugins/form_text_render/info.txt
./plugins/pp_io/info.txt
./plugins/pp_io/parallelppdev.py
./plugins/pp_io/pp_io.html
./plugins/pp_io/pp_io_large.png
./plugins/pp_io/pp_io.png
./plugins/pp_io/pp_io.py
./plugins/video_player/info.json
./plugins/video_player/video_player_large.png
./plugins/video_player/video_player.md
./plugins/video_player/video_player.png
./plugins/video_player/video_player.py
./qt.conf
./README.txt
./resources/templates/eco_alt_template.opensesame.tar.gz
./setup-android.py
./setup-mac.py
./setup-win32.py
```
so if we use those for .orig.tar.gz, dpkg-source would fail since there are additional files in the debian branch from which packaging is done.  We could list them all but that is imho undue pain.  Thus imho the simplest resolution, which is what I usually do at least, is use complete tarballs of the source repository, e.g. as provided by github for tagged releases, and which would be fetched by uscan now (debian/watch points to github).  Then the only difference will be the content of debian/ and we would be kosher.  

So for releases workflow is easy:
- tag release in release branch, push the tag to github
- uscan --verbose --rename (to fetch tarball for that tag and rename it to .orig...)
- dch -i    to create a new changelog entry with matching release version
- gbp buildpackage   to build package and it would use that .orig.tar.gz

for "snapshot" builds, could also be easily done ;)
- merge snapshot (better based on "git describe <commit>" description), e.g.
```
$> git describe --tags origin/heisenberg 
release/2.9.6-25-gd1a1dc4
```
N.B. you better use annotated tags for your releases!

```git merge release/2.9.6-25-gd1a1dc4```  -- now leads to conflict in debian/changelog which is a bit weird since ideally you just keep debian/ in debian branch
- dch -i    to create a new changelog entry of format (in my  case generated by `dch_gitrev -i release/2.9.6-25-gd1a1dc4`  source for the helper is at http://git.onerussian.com/?p=etc/bash.git;a=blob;f=.bash/bashrc/30_aliases_sh;hb=HEAD#l284  but you need annotated tags, or add --tags to describe there)

```
+opensesame (2.9.7~pre2+git25-gd1a1dc4-1) unstable; urgency=medium
+
+  * New upstream snapshot from release/2.9.6-25-gd1a1dc4
+
+ -- Yaroslav Halchenko <debian@onerussian.com>  Mon, 27 Jul 2015 12:27:02 -0400
```

commit it and should be all set to go with gbp buildpackage -- it will not find .orig.tar.gz and will generate it automagically from that  d1a1dc4  treeish.

uff -- came out a bit long, but hopefully useful ;)

**Pull request merged**
