### PR TITLE
text_input: ability to move caret

### PR DESCRIPTION
**Pull request by dcnieho**
Needed to be able to move caret around in inputted text. Can now process leftward and rightward arrow key to move in inputted string. Also added processing of delete key as caret can now be in middle of string. Very 1980s feel i know (even the Windows terminal has a less nerdy caret), but hey!

### CODE REVIEW

**Comment by smathot** [comment]
Hi Diederick,

Thanks for your contribution(s)! I'm a little unsure about this one. It's definitely better than it was. But still not satisfactory, because the cursor goes in between the letters, instead of under them. I'm inclined to either fix it properly, or leave it for the moment. Do you have any idea that is not too invasive (heisenberg receives only minor maintenance updates) and would fix the cursor issue?

Also, as a small point, please take a look at the style guidelines, i.e. no camelCase and a 80 character limit. It makes my OCD play up, and it's better to be consistent from the start.

- http://osdoc.cogsci.nl/contribute/develop/#coding-style-guidelines

Cheers,
Sebastiaan

**Comment by dcnieho** [comment]
Hi Sebastiaan,

Prima, OCD is a good thing as a programmer. Do you prefer a new, clean pull
request, or just another commit to fix formatting?

As for your point about fixing it properly, from my little insight into the
code base, a proper fix looks like a lot of work. I considered also doing
vertical caret movements, but that already looked like a real bitch given
info about placement of individual characters seemed not readily available
from canvas (I think... what do i know really?). Underlining instead of
inserting the caret would also be difficult as far as i can see, unless it
is possible to hack that with a unicode composing character (quick search
came up empty).

What do you understand by a proper fix by the way? A real proper fix would
be an input box that acts and feels the way a box in e.g. a browser does.
Perhaps a Qt panel if that plays nicely with the backend's surface.

In the end, this little bit of code made things significantly more usable
for me (typing texts of more than a few words), so perhaps it is a step
forward on the way to a proper fix.

Cheers,
Died

On Wed, Mar 18, 2015 at 6:00 PM, Sebastiaan Mathot <notifications@github.com

**Comment by smathot** [comment]
I thought about it for a bit, and I think it's best to integrate your solution. Not being able to move the cursor is really annoying, so this is at least a crude workaround for now.

> Do you prefer a new, clean pull request, or just another commit to fix formatting?

Whatever is easiest for you.

> A real proper fix would be an input box that acts and feels the way a box in e.g. a browser does. Perhaps a Qt panel if that plays nicely with the backend's surface.

The problem is that you cannot use Qt, or similar widget toolkits, on your own window surface. That is, a Qt widget cannot coexist with, say, a PsychoPy stimulus in a single window That's why forms have been implemented from the ground up, using the back-end specific drawing routines. This works, but is much less efficient and flexible.

Cheers,
Sebastiaan

**Comment by dcnieho** [comment]
Cool! I have updated the pull request. I see it looks shitty in the github diff, but looks fine in my editor that uses for spaces per tab for display. That ok?

**Comment by smathot** [comment]
Merged into `heisenberg`. Thanks again!

**Pull request closed without merging**
